erdos-project/pylot

- data_gatherer.py
- pylot/loggers/camera_logger_operator.py
- pylot/loggers/lidar_logger_operator.py
- pylot/simulation/carla_legacy_operator.py
- scripts/convert_carla_to_coco.py
- Script for generating COCO annotations from CARLA data.
- Log depth camera information.
- Log LIDAR information.
> Add basic functionality for data gathering.

- pylot/perception/detection/utils.py
- pylot/simulation/carla_operator.py
- pylot/simulation/perfect_detector_operator.py
- pylot/simulation/utils.py
Use ground truth segmentation to extract traffic sign bounding boxes, then use ground truth traffic light location data to map bounding boxes to traffic light colors for logging and visualization.
When visualizing traffic light bounding boxes, the boxes will be red, yellow, or green depending on the state of the traffic light.
> Added logging and visualization for traffic light bounding boxes.

- pylot/simulation/perfect_detector_operator.py
- pylot/simulation/utils.py
- scripts/check_3d_2d_conversions.py
Fixed bugs and added documentation for transforms.
> Fixed bugs and added documentation for transforms.

- pylot.py
- pylot/config.py
- pylot/debug/depth_camera_visualizer.py
- pylot/debug/depth_estimation_operator.py
- pylot/operator_creator.py
- pylot/perception/depth_estimation/depth_est_operator.py
- pylot/perception/messages.py
- pylot/simulation/challenge/ERDOSAgent.py
- pylot/utils.py
ionel, I just synced with the repo so that there's less stuff to check if you want to merge the changes
> depth estimation operator (cleaned up)

- configs/data_gatherer.conf
- configs/data_gatherer_autopilot.conf
- data_gatherer.py
- pylot.py
- pylot/config.py
- pylot/loggers/trajectory_logger_operator.py
- pylot/operator_creator.py
- pylot/perception/fusion/fusion_operator.py
- pylot/perception/messages.py
- pylot/simulation/carla_utils.py
- pylot/simulation/perfect_detector_operator.py
- pylot/simulation/perfect_tracker_operator.py
- pylot/simulation/utils.py
- pylot/utils.py
Adds functionality for perfect tracking of other vehicles in the environment. Locations of vehicles are calculated and logged with respect to the ego vehicle.
> Add tracking for other vehicles.

- pylot/simulation/perfect_tracker_operator.py
Logs trajectories of pedestrians with respect to the ego vehicle.
> Add tracking for pedestrians.

- pylot.py
- pylot/operator_creator.py
- pylot/simulation/messages.py
- pylot/simulation/perfect_lane_detector_operator.py
- pylot/simulation/utils.py
- Added a PerfectLaneDetectionOperator that takes in the current location and retrieves waypoints for the ego vehicle's lane markings until the end of the road.
- Added the operator to the set of perfect detection operators.
- Introduced a new type for a LaneDetected message (note that the previous LaneDetectionOperator did not have a LaneDetection message, and was sending a copy of the image to the downstream operators.)
> Implemented the perfect lane detector operator.

- scripts/create_obj_detection_tf_records.py
Adds script for converting data to TFRecords, to use for training object detection models.
> Object detection preprocessing script

- configs/data_gatherer.conf
- configs/data_gatherer_autopilot.conf
- configs/segmentation.conf
- data_gatherer.py
- pylot.py
- pylot/config.py
- pylot/debug/segmented_top_down_video_operator.py
- pylot/loggers/camera_logger_operator.py
- pylot/operator_creator.py
- pylot/utils.py
- Added logging and visualization for a top-down segmentation camera, along with a flag controlling how far to the left and right the camera can view. (This camera will be used later for visualizing tracking.)
- Fixed inconsistencies in camera naming and moved camera names to pylot/utils.py
> Add top-down segmentation camera

- configs/top_down_tracking.conf
- pylot.py
- pylot/config.py
- pylot/debug/track_visualize_operator.py
- pylot/operator_creator.py
- pylot/simulation/utils.py
- pylot/utils.py
Adds a visualizer from a top-down perspective for trajectories of other agents.
> Add visualization for top-down tracking.

- data_gatherer.py
- pylot.py
- pylot/operator_creator.py
Fixed data gatherer script to correctly add visualization operators.
> Fix for adding visualization operators

- configs/data_gatherer_chauffeur.conf
- data_gatherer_chauffeur.py
- pylot.py
- pylot/config.py
- pylot/loggers/chauffeur_logger_operator.py
- pylot/operator_creator.py
- pylot/perception/segmentation/utils.py
- pylot/simulation/perfect_tracker_operator.py
- pylot/utils.py
This PR implements a logger in ChauffeurNet format (missing traffic lights). It builds upon @alvkao58 's visualization operator and logs top down, separated semantic images with past pose profiles of tracked objects.
> [WIP] adding ChauffeurNet logger 

- data_gatherer_chauffeur.py
- pylot/loggers/chauffeur_logger_operator.py
- pylot/utils.py
@ICGog I have added some code for logging traffic lights.
Commit 547a4f1 draws traffic light boxes in the world, then uses a top-down camera to record masks of those boxes. There are a couple issues I'm not sure how to address:
- I don't think I'm using the traffic lights stream data properly (not using the data, just using it to draw extent boxes whenever a message comes in).
- Seems like the colors I use to draw the boxes are not the exact same colors on the frames coming from the top down camera stream.
> Traffic light ChauffeurNet logging

- configs/imu.conf
- data_gatherer.py
- pylot.py
- pylot/config.py
- pylot/loggers/imu_logger_operator.py
- pylot/operator_creator.py
Adding IMU logger that logs transform, acceleration, gyro, orientation.
> adding imu logger

- pylot/simulation/sensor_setup.py
- pylot/utils.py
- tests/test_transforms.py
Added tests for the functionality in https://github.com/erdos-project/pylot/blob/erdust/pylot/perception/depth_frame.py, and fixed bug in the CameraSetup's intrinsic matrix.
> added tests for DepthFrame class

- pylot/perception/depth_frame.py
- pylot/perception/point_cloud.py
- pylot/simulation/sensor_setup.py
- pylot/utils.py
- tests/test_transforms.py
Adds unit tests for functionality in PointCloud class, as well as clarifying comments about coordinate axis orientation.
> Tests for PointCloud

- requirements.txt
- scripts/check_3d_2d_conversions.py
- setup.py
Update+refactor script for using LIDAR and depth camera to calculate the world location of a query pixel.
> Script for checking 2d-3d conversions

- configs/imu.conf
- requirements.txt
- setup.py
Covers and addresses the comments in https://github.com/erdos-project/pylot/pull/54
Creating a new PR because of git permission changes.
> Removing log_imu and updating requirements

- requirements.txt
- scripts/check_3d_2d_conversions.py
- setup.py
Removes dependency on python3-tk introduced in #55, because of issues as raised in #57.
> remove dependency on python3-tk in scripts

- install.sh
- pylot.py
- pylot/component_creator.py
- pylot/flags.py
- pylot/operator_creator.py
- pylot/perception/detection/detection_eval_operator.py
- pylot/perception/tracking/da_siam_rpn_tracker.py
- pylot/perception/tracking/object_tracker_operator.py
- pylot/perception/tracking/tracking_eval_operator.py
- requirements.txt
Ignore commit 3583f81 for now, still working on that. Also, please let me know if I should add docs or unit tests anywhere.
> Tracking updates

- data_gatherer.py
- pylot/debug/track_visualizer_operator.py
- pylot/loggers/chauffeur_logger_operator.py
- pylot/perception/depth_frame.py
- pylot/perception/detection/utils.py
- pylot/perception/point_cloud.py
- pylot/simulation/perfect_tracker_operator.py
- pylot/simulation/utils.py
- pylot/utils.py
- tests/test_point_cloud.py
Addresses performance issues discussed in #28 by avoiding unnecessary conversions for point clouds between a numpy array and a list of locations.
> Address point cloud performance issues.

- pylot/map/hd_map.py
- pylot/perception/messages.py
- pylot/planning/utils.py
- pylot/planning/waypoint_planning_operator.py
- pylot/simulation/challenge/ERDOSAgent.py
- pylot/simulation/challenge/ERDOSTrack4Agent.py
Parses the ground_objects input data and converts the given GPS coordinates to our world coordinates, then feeds the input into our existing waypoint planning operator/PID controller.
> [WIP] Track 4 Operator

- pylot/simulation/challenge/ERDOSAgent.py
Similar to the track 4 agent, send the top watermark for the open drive stream in run_step, whenever we don't have access to the open drive map.
> Fix OpenDrive top watermark for challenge agent.

- configs/frenet_optimal_trajectory_planner.conf
- pylot/control/flags.py
- pylot/control/pid_agent_operator.py
- pylot/flags.py
- pylot/planning/flags.py
- pylot/planning/frenet_optimal_trajectory/flags.py
- pylot/planning/frenet_optimal_trajectory/fot_planning_operator.py
Refactoring the pylot operator to load hyperparameters from flags and use the new frenet implementation: https://github.com/erdos-project/frenet_optimal_trajectory_planner
https://drive.google.com/file/d/1fQfBExyZVwPWdnHgfrEHw6Eecrci_sED/view
> Updating pylot to use refactored frenet planner

- data_gatherer.py
- pylot.py
- pylot/control/control_eval_operator.py
- pylot/control/mpc/mpc_agent_operator.py
- pylot/control/pid_agent_operator.py
- pylot/operator_creator.py
- pylot/planning/utils.py
- pylot/planning/waypoint_planning_operator.py
- pylot/simulation/carla_operator.py
- pylot/simulation/flags.py
- pylot/simulation/planning_pose_synchronizer_operator.py
- scenario_runner.py
- scripts/compute_decay.py
- CarlaOperator now publishes a pose_stream_for_control (data is published only in pseudo-asynchronous mode for now)
- A new PlanningPoseSynchronizerOperator is introduced for pseudo-asynchronous mode that publishes synchronized waypoints and pose streams for the control operator but also logs the runtime of the pipeline and delays the application of waypoints by the runtime.
- Fixes to other parts of the pipeline to adjust to the new streams.
- This change moves the remove_completed_waypoints function from the waypoint_planning operator to the utils.
- remove_completed_waypoints is called by the control operator to trim waypoints until the new waypoints are received through the pipeline.
- The lookahead for both speed and steer is now decided based on the current speed of the vehicle in …
> Introduce a high-frequency control loop.

- install.sh
- pylot.py
- pylot/component_creator.py
- pylot/drivers/sensor_setup.py
- pylot/flags.py
- pylot/operator_creator.py
- pylot/prediction/flags.py
- pylot/prediction/r2p2_predictor_operator.py
- pylot/simulation/perfect_tracker_operator.py
- scenario_runner.py
Operator for a single-agent version of the trajectory forecasting algorithm R2P2 (https://people.eecs.berkeley.edu/~nrhinehart/papers/r2p2_cvf.pdf).
> Operator for R2P2

- pylot.py
- pylot/loggers/eval_metric_logger_operator.py
- pylot/operator_creator.py
- scenario_runner.py
For obstacle heatmaps, trajectory comparison, etc.
> Adding pose / obstacle logging to eval metrics

- pylot/loggers/eval_metric_logger_operator.py
I accidentally used commas in my lists which messes up CSV logging.
> fixing CSV logging

- configs/scenarios/person_avoidance_rrt.conf
- configs/scenarios/person_crossing_frenet.conf
- configs/scenarios/person_crossing_rrt.conf
- pylot/planning/rrt_star/rrt_star_planning_operator.py
Small bug fix when passing hyper parameters and updating the RRT* configs to work in the person behind car scenario.
> updating RRT operator and configs, small bug fix

- pylot/drivers/sensor_setup.py
- pylot/simulation/utils.py
- pylot/utils.py
Fixes lidar to unreal transform in LidarSetup, as well as miscellaneous typos.
> [Bug] Fix lidar to unreal transform and typos.

- pylot.py
- pylot/component_creator.py
- pylot/debug/visualizer_operator.py
- pylot/drivers/carla_camera_driver_operator.py
- pylot/flags.py
- pylot/operator_creator.py
- pylot/perception/depth_frame.py
- pylot/simulation/synchronizer_operator.py
- pylot/utils.py
- Uses `pygame` to visualize different modules of the pipeline, and provides a status box on the top to show the current speed, time and the control of the ego-vehicle.
[https://drive.google.com/file/d/1JSAbIfWIDplzvF8RKVEOz_XaFMkQeoAb/view?usp=sharing](url)
> Introduce a new VisualizerOperator

- data_gatherer.py
- pylot.py
Match the API change [ERDOS 0.3.1](https://github.com/erdos-project/erdos/blob/96613916a320d447e16af79b554bcbbdb7a11e8c/python/erdos/__init__.py#L151).
> [Bug] Rename node_handle.wait() to node_handle.join()

- pylot/perception/detection/lanenet_detection_operator.py
Fixes #154 along with ICGog/lanenet-lane-detection#1.
> Fix lanenet imports

- requirements.txt
- setup.py
> Update open3d version to 0.7.0.0

- .github/workflows/ci.yml
Set yapf and flake8 versions to match the container
> [CI] Enable CI for all PRs, fix yapf to 0.31.0, flake8 to 3.9.2

- .github/workflows/ci.yml
- detection_operator_runner.py
- pylot/perception/detection/detection_operator.py
- pylot/perception/messages.py
* Adds `detection_operator_runner.py` to test operator changes
* Update `detection_operator.py` to erdos redesign operator style
> [Redesign] Update detection operator

- detection_operator_runner.py
- pylot/perception/detection/efficientdet_operator.py
> Efficientdet redesign

- detection_operator_runner.py
- pylot/perception/depth_estimation/depth_estimation_operator.py
* Run the script with an added flag to select operator to test
`python detection_operator_runner.py --test_operator depth_estimation`
* Add Depth, Segmentation, and Left/Right cameras for future operators
* Update `DepthEstimationOperator` which uses Left/Right cameras
> [Redesign] Add Flags, More Cameras, DepthEstimationOperator

- detection_operator_runner.py
- pylot/perception/messages.py
- pylot/perception/tracking/qd_track_operator.py
* Update `QdTrackOperator` to redesign
> [Redesign] Update Qdtrack operator

- detection_operator_runner.py
- pylot/perception/messages.py
- pylot/perception/segmentation/segmentation_decay_operator.py
- pylot/perception/segmentation/segmentation_drn_operator.py
- pylot/perception/segmentation/segmentation_eval_operator.py
* Update `SegmentationEvalOperator`, `SegmentationDRNOperator`, and `SegmentationDecayOperator` to redesign
* dependencies/drn/segment.py needs update for use with py3.7
> [Redesign] Update segmentation operators

- detection_operator_runner.py
- pylot/loggers/bounding_box_logger_operator.py
- pylot/loggers/camera_logger_operator.py
- pylot/loggers/multiple_object_tracker_logger_operator.py
* Updates to `BoundingBoxLoggerOperator`, `CameraLoggerOperator`, and `MultipleObjectTrackerOperator`
> [Redesign] Update Simple Logger Operators

- detection_operator_runner.py
- pylot/component_creator.py
- pylot/operator_creator.py
- pylot/perception/detection/obstacle_location_finder_operator.py
- pylot/perception/fusion/fusion_operator.py
- pylot/perception/tracking/center_track_operator.py
* Also, updates to `operator_creator` functions for obstacle tracking
> [Redesign] Update ObstacleLocationFinderOperator, FusionOperator

- detection_operator_runner.py
- pylot/operator_creator.py
- pylot/prediction/prediction_eval_operator.py
* Type checking on multi-input streams does not work for `List[ObstaclePrediction]`
> [Redesign] Update PredictionEvalOperator
