erdos-project/pylot

pylot/simulation/carla_operator.py

- Always drive vehicle that is used in the Carla Challenge.
- Make sure that we spawn in an unoccupied spawn position.

Fixes to spawning driving vehicle.

---

pylot/simulation/utils.py

Make sure vertices of logged bounding boxes don't go off screen, so that we have proper bounding boxes for object detection.

make sure logged bounding boxes don't go off screen

---

configs/prediction.conf
pylot.py
pylot/config.py
pylot/debug/track_visualize_operator.py
pylot/operator_creator.py
pylot/prediction/linear_predictor_operator.py
pylot/prediction/messages.py
pylot/utils.py

Addresses #32.
* Adds operator that fits a linear model (at+b, ct+d) to past (x,y) locations of each agent.
* Modifies the existing trajectory visualizer to also visualize predicted trajectories.

Add linear predictor operator and visualization for prediction

---

configs/imu.conf
pylot.py
pylot/config.py
pylot/debug/imu_visualizer_operator.py
pylot/operator_creator.py
pylot/simulation/imu_driver_operator.py
pylot/simulation/messages.py
pylot/simulation/utils.py
pylot/utils.py

Adding the Carla IMU sensor: https://carla.readthedocs.io/en/latest/cameras_and_sensors/#sensorotherimu
The IMU sensor is setup similarly to `camera_driver_op` / `lidar_driver_op` and publishes to the `sensor.other.imu` stream. It publishes `transform (carla.Transform), acceleration (carla.Vector3D), gyro (carla.vector3D), compass (orientation relative to Unreal North (0, -1, 0))`. This stream can be filtered using the `is_imu_stream` utility in `pylot.utils`.
Note that this only works on the master branch, as the IMU sensor was added recently. To build the master branch follow: https://carla.readthedocs.io/en/latest/how_to_build_on_linux/ and set the `CARLA_HOME` path appropriately.
Video: https://drive.google.com/open?id=1yfW0XPH8-y8fYtkS2y_ex4DmrUc4aZAL

Adding IMU sensor

---

pylot.py
pylot/config.py
pylot/debug/prediction_visualize_operator.py
pylot/operator_creator.py
pylot/planning/rrt_star/rrt_star_planning_operator.py

Adding a visualizer OP that draws the predicted future poses in the world.
Also moving the can_bus visualizer OP into the add_visualization_operators function.
Also makes small fix to RRT* obstacle map building (predictions were assumed to be global but are really ego centric)
Demo: https://drive.google.com/open?id=1HUOtteAvd-vX21L5hstX1uwsXGUTEsGC

adding prediction visualizer

---

requirements.txt
setup.py

Found a small issue in our current `setup.py` and `requirements.txt` files. The package `python3-tk` doesn't exist in `pip`, which leads to 
```HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/python3-tk/``` when trying to install via `pip install python3-tk`. This PR removes the `python3-tk` package (as it should be included or available via `apt-get update`).

removing python3-tk from requirements

---

pylot/control/mpc/utils.py

Found this when I was porting code to C++, the 1st term in the equation would be rounded to 0 due to Python 2 division. Not sure if we care because Python 2 is being deprecated and we have switched to Python 3? Feel free to close this if that's the case.

fixing int division bug in CSP1D

---

.gitignore
configs/frenet_optimal_trajectory_planner.conf
pylot/operator_creator.py
pylot/planning/frenet_optimal_trajectory/fot_planning_operator.py
pylot/utils.py

Adding `flow_watermarks=False` in the PID agent operator creator fixed the following issue:
```
Traceback (most recent call last):
File "/home/edward/Desktop/erdos/python/erdos/__init__.py", line 175, in internal_watermark_callback
callback(timestamp, *write_streams)
File "/home/edward/Desktop/erdos/python/erdos/__init__.py", line 185, in _flow_watermark_callback
write_stream.send(WatermarkMessage(timestamp))
File "/home/edward/Desktop/erdos/python/erdos/streams.py", line 130, in send
return self._py_write_stream.send(internal_msg)
Exception: Error sending message on ingest stream fd04598a-4590-b39f-1db1-065697be09e1: TimestampError
```
To solve the math domain error when computing rotations in `Transform`, added a `np.clip(..., 0, 1)`. I verified that the values were indeed extremely …

Fixing flow watermarks, math domain error

---

.gitignore
configs/rrt_star_planner.conf
install.sh
lincoln.py
pylot/component_creator.py
pylot/operator_creator.py
pylot/planning/rrt_star/rrt_star_planning_operator.py

This PR updates `rrt_star_planning_operator.py` to use the C++ version of RRT*. The runtime of the operator ranges from ~10-30ms in normal cases where it finds a solution, but can take up to ~250ms in the case it can't find a solution. These numbers were collected using step sizes of 0.5 meters and 2000 max iterations. We can tune it to be better in worst case scenario.
It's complemented by a bug fix in the C++ RRT* relating to Python / C++ array memory access in ctypes. Here is a link to the PR: https://github.com/erdos-project/rrt_star_planning/pull/2
Video of working demo: https://drive.google.com/open?id=1noHwj8et5jgQBjf63oY8byzOuzlt78Dc

Updating RRT* Operator to use C++ RRT* wrapper

---

pylot/perception/point_cloud.py
tests/test_point_cloud.py

The previous code would normalize the point cloud, and find the point closest to our 2D point transformed to 3D. However, this would fail because the closest point may not be near the same (x, y) coordinate. This fix utilizes just the (x, y) coordinate to figure out the closest point in the point cloud, and utilizes its z-value instead of normalizing.
Also, we don't have to take the unreal transform if we are driving the real vehicle.

Fixes the LIDAR depth perception for Lincoln MKZ.

---

pylot/component_creator.py
pylot/control/control_eval_operator.py
pylot/flags.py
pylot/operator_creator.py

Implements two metrics for control evaluation:
1. Crosstrack error : Difference between the desired and achieved waypoint.
2. Heading error: Angle between the heading of the vehicle and the heading desired by the reference waypoints.
The metrics were discussed [here](https://www.coursera.org/lecture/intro-self-driving-cars/lesson-1-introduction-to-lateral-vehicle-control-pTs75).

Adds metrics for control evaluation.

---

configs/scenarios/eval_person_avoidance_rrt.conf

This was missing from the `eval_person_avoidance_rrt.conf`

adding planning type to rrt conf

---

configs/scenarios/tracker_evaluation.conf
pylot/perception/tracking/da_siam_rpn_tracker.py
pylot/perception/tracking/deep_sort_tracker.py
pylot/perception/tracking/sort_tracker.py

- Trackers should all track properly, even when an empty obstacles message is received.
- Trackers all use the same default hyperparameters (min/max matching iou threshold, max tracker age, etc.)
- Fixed a deepsort bug that resulted in too many updates, lowering mota unecessarily

Tracking allow missed detections

---

configs/scenarios/person_avoidance_frenet.conf
configs/scenarios/person_crossing_frenet.conf

Obstacle radius was too penalizing, causing frenet to fail when it could have found a solution. We can get around this by using the inverse distance to obstacle cost, `ko`, and increasing the prediction steps.

Updating person crossing and person avoidance config

---

tests/requirements.txt
tests/test_point_cloud.py

The logic for calculating pixel locations in LIDAR is different for CARLA and for Lincoln MKZ (see https://github.com/erdos-project/pylot/blob/ff4cc6634afa9618aecdcc39509faa26eb51eb67/pylot/perception/point_cloud.py#L78).
Therefore, we revert the reference values for testing the pixel location calculations to their original values for CARLA.

Fix for point cloud tests.

---

pylot/component_creator.py
pylot/operator_creator.py
pylot/planning/utils.py
pylot/prediction/flags.py
pylot/prediction/r2p2_predictor_operator.py
pylot/simulation/perfect_tracker_operator.py
pylot/utils.py

Extends R2P2 to the multi-agent case, outputting predictions for all vehicles within a specified radius. 
For each vehicle, the operator rotates the ego-vehicle's LIDAR point cloud, as well as the vehicle's past trajectory, to that vehicle's coordinate frame before performing inference. Orientations of vehicles are estimated using the past two locations of the vehicle. R2P2 inherently does not perform any joint modeling of agents.

Added multi-agent support to R2P2

---

pylot/control/mpc/mpc.py
pylot/control/mpc/mpc_operator.py

- MPCOperator used `self._config` which is reserved by the `OperatorConfig`, causing errors with the logging.
- Make MPC use the latest waypoint APIs which also fixes some errors.
- Use `@` instead of `*` for cvxpy matrix multiplication to suppress warning messages.

Fix MPC bugs

---

pylot/perception/detection/utils.py

Because tuples are sorted lexicographically, when the first entries in the tuples (confidence) are equal, the second entries (bbox objects) are compared. This leads to the following error:
```
Traceback (most recent call last):
File "/home/eyal/.local/lib/python3.6/site-packages/erdos/__init__.py", line 195, in internal_watermark_callback
callback(timestamp, *write_streams)
File "/home/eyal/pylot/pylot/perception/detection/detection_eval_operator.py", line 84, in on_watermark
ground_obstacles, obstacles)
File "/home/eyal/pylot/pylot/perception/detection/utils.py", line 467, in get_mAP
confidence_bbox.sort()
TypeError: '<' not supported between instances of 'BoundingBox2D' and 'BoundingBox2D'
```
This fix achieves the same effect but gets around this issue.

[mAP computation] Fix error when confidences are equal, and condensed code

---

configs/perfect_lane_detection.conf
pylot/map/hd_map.py
pylot/simulation/perfect_lane_detector_operator.py

* Added lane detection config that uses the perfect lane detection operator with `--perfect_lane_detection` flag
These changes will fix the errors when using the perfect lane detection flag: 
* fixed some bugs with fetching lanes in `get_lane`  because of missing parameters.
* id in Lane output will be set to 0 by default in `get_lane`
* add ability to get all lanes using `get_all_lanes` function and the approach described in meetings

perfect lane detection config

---

requirements.txt
setup.py

Sets pygame version to `pygame==1.9.6`, as newer version of pygame cause errors with X errors in docker.
See #152 for more details on the errors.

Fix pygame version

---

pylot/perception/flags.py
pylot/perception/tracking/tracking_eval_operator.py

Decoupling the min IOU used by the tracker for ID matching between frames, versus the min IOU used by the tracking eval to match predictions with ground truth.

eval min matching iou

---

pylot/flags.py
pylot/loggers/bounding_box_logger_operator.py
pylot/loggers/camera_logger_operator.py
pylot/loggers/chauffeur_logger_operator.py
pylot/loggers/gnss_logger_operator.py
pylot/loggers/imu_logger_operator.py
pylot/loggers/lidar_logger_operator.py
pylot/loggers/multiple_object_tracker_logger_operator.py
pylot/loggers/pose_logger_operator.py
pylot/loggers/trajectory_logger_operator.py

Organizes logs into folders for easier navigation and debugging.
For example, after 2 runs the data directory might be organized as follows:
```
data
├── 2021-06-03T23:45:28
│   ├── center camera
│   │   ├── center camera-5896.png
│   │   └── center camera-6196.png
│   ├── center depth camera
│   │   ├── center depth camera-5896.pkl
│   │   └── center depth camera-6196.pkl
│   ├── center lidar
│   │   ├── center lidar-5896.ply
│   │   └── center lidar-6196.ply
│   ├── center segmented camera
│   │   ├── center segmented camera-5896.png
│   │   └── center segmented camera-6196.png
│   ├── gnss
│   │   ├── gnss-5896.json
│   │   └── gnss-6196.json
│   ├── imu
│   │   ├── imu-5896.json
│   │   └── imu-6196.json
│   └── right camera
│       ├── right camera-5896.png
│       └── right …
```

Organize logs into folders

---

pylot/simulation/carla_operator.py
pylot/simulation/utils.py

Fixes a bug where using a custom port for the CARLA traffic manager would result in the following error:
```RuntimeError: trying to create rpc server for traffic manager; but the system failed to create because of bind error.```
This error occurs because `command.SetAutopilot` and `ego_vehicle.set_autopilot` expect a `traffic_manager_port` argument which defaults to 8000.
This fix passes the correct traffic manager port as specified in Pylot's flags to these functions.

[Bug] Support custom CARLA traffic manager ports

---

pylot/perception/detection/lane.py
pylot/perception/detection/lanenet_detection_operator.py

See discussion in https://github.com/erdos-project/pylot/pull/244#issue-1190475568.
- Transform class is not necessary to represent lane markings since Rotation is not considered/computed in either the perfect lane detection operator or the lanenet operator. 
- Disentangle dependency on Transform in the Lane object and the lanenet operator.

Use Location instead of Transform for representing Lane markings

---

docker/Dockerfile
install.sh

Enables access to programs installed via pip (e.g. maturin, ipython) without requiring `pip install --user`.

[Docker] Add ~/.local/bin to $PATH

---

pylot/simulation/utils.py

I have tested on multiple towns and found that if the number of NPC vehicles is large (e.g., 100), then it's very likely to get stuck on the spawning ego vehicle. One possible condition to trigger this is that those NPC vehicles have taken the spawn point of the ego vehicle.
Spawning the ego vehicle first could be a more robust implementation.

Switch spawning order between ego and NPC vehicles
